[general]
dataset = "wine"
experiment_name = ""
experiment_variable = "missing_percent"
missing_percent = [0.05, 0.1, 0.15, 0.2, 0.25]				# share of missing values generated
missing_outliers = 0.2							# share of missing values, that were outliers in the original distribution
missing_value_features = 0						# number of additional features that will have missing values generated
missing_value_mask = -1000
random_seed = 123456
runs = 100

[outlier_definition]
st_deviations = 1.5							# nr. of std deviations to identify point as outlier
min_outliers_per_direction = 0.05					# minimum requried share of outliers in each direction
min_outliers_total = 0.15						# minimum requried share of outliers in total

[DBSCAN]
eps = ""
min_samples = ""

[RQ2]
pred_features = 1

[regressor_param]
#optimizer_fn = torch.optim.Adam
#scheduler_fn = torch.optim.lr_scheduler.StepLR
#scheduler_params = {'step_size': 0.2, 'gamma': 0.9}
#mask_type = "entmax"

[training]
train_val_split = 0.75
cl_weights = [1,1,0] 							# Explanation: [RMSE, KLDiv, Cluster-Mean-Loss]

[model_param]
max_epochs = 250
patience = 50
eval_metric = ["custom_loss"]

[plots]
dpi = 300