[general]
dataset = "wine"							# currently implemented: "iris", "wine", "drybean"
experiment_name = "RQ3_decision_tree"
experiment_variable = "missing_percent"
missing_percent = [0.2]							# share of missing values generated
missing_outliers = 0.2							# share of missing values, that were outliers in the original distribution
missing_value_features = 0						# share of additional features that will have missing values generated
missing_value_mask = -1000
random_seed = false
seed_train_test_split = false
models = 5								# number of models trained, median of the models predictions will be used
runs = 10								# number of randomly created missing-value datasets to do predictions on

[outlier_definition]
st_deviations = 1.5							# nr. of std deviations to identify point as outlier
min_outliers_per_direction = 0.05					# minimum required share of outliers in each direction
min_outliers_total = 0.15						# minimum required share of outliers in total

[DBSCAN]
eps = ""
min_samples = ""

[RQ2]
n_omitted_features = 0							# features omitted in %

[regressor_param]
# config in jupyter notebook

[training]
train_val_split = 0.75
cl_weights = [1,1,0] 							# Explanation: [RMSE, KLDiv, Cluster-Mean-Loss]

[model_param]
max_epochs = 250
patience = 50
eval_metric = ["custom_loss"]

[plots]
dpi = 300