[general]
experiment_name = ""
missing_percent = [0.0, 0.15, 0.1]
missing_value_mask = -1
random_seed = false

[toy_data]
n_features = 3
n_samples = [50, 100, 50]
centers = [[1, 5, 1], [7, 12, 9], [10, 2, 5]]
cluster_std = 1.5

[DBSCAN]
eps = 3
min_samples = 5

[RQ2]
pred_features = 1
runs = 1

#[regressor_param]
#optimizer_fn = torch.optim.Adam
#scheduler_fn = torch.optim.lr_scheduler.StepLR
#scheduler_params = {'step_size': 2, 'gamma': 0.9}
#optimizer_params = {'lr': 0.02}
#mask_type = "entmax"

[training]
train_val_split = 0.75

[model_param]
max_epochs = 300
patience = 50

[plots]
dpi = 300