[general]
experiment_name = "100_runs_max-epochs_rmse"
experiment_variable = "max_epochs"
missing_percent = [0.0, 0.15, 0.1]
missing_value_mask = -1
random_seed = 1141386077
use_toy_data = true

[toy_data]
n_features = 3
n_samples = [50, 100, 50]
centers = [[1, 5, 1], [7, 12, 9], [10, 2, 5]]
cluster_std = 1.5

[DBSCAN]
eps = 3
min_samples = 5

[RQ2]
pred_features = 1
runs = 100

#[regressor_param]
#optimizer_fn = torch.optim.Adam
#scheduler_fn = torch.optim.lr_scheduler.StepLR
#scheduler_params = {'step_size': 2, 'gamma': 0.9}
#optimizer_params = {'lr': 0.02}
#mask_type = "entmax"

[training]
train_val_split = 0.75

[model_param]
max_epochs = [100, 150, 200, 250, 300, 350, 400]
patience = 50
eval_metric = ["rmse"]

[plots]
dpi = 300
#[regressor_param]
#optimizer_fn = <class 'torch.optim.adam.Adam'>
#optimizer_params = {'lr': 0.05}
#scheduler_params = {'step_size': 2, 'gamma': 0.9}
#scheduler_fn = <class 'torch.optim.lr_scheduler.StepLR'>
#mask_type = entmax
#device_name = cuda
#verbose = 0
