[general]
experiment_name = "wine_100runs_mask-values_3mv-features_custom-loss-weighted"
experiment_variable = "missing_value_mask"
missing_percent = [ 0.0, 0.15, 0.0, 0.0, 0.2, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
missing_value_mask = [ 1000000000000, 1000, 100, 10, 1, -1, -10, -100, -1000, -1000000000000,]
random_seed = 435503985
use_toy_data = false

[toy_data]
n_features = 3
n_samples = [ 50, 100, 50,]
centers = [ [ 1, 5, 1,], [ 7, 12, 9,], [ 10, 2, 5,],]
cluster_std = 1.5

[DBSCAN]
eps = 2
min_samples = 26

[RQ2]
pred_features = 1
runs = 100

[training]
train_val_split = 0.75
cl_weights = [ 0.5, 1.0, 0.0001,]

[model_param]
max_epochs = 250
patience = 50
eval_metric = [ "custom_loss",]

[plots]
dpi = 300
